language: go
sudo: false
dist: trusty
go:
  - tip
addons:
  apt:
    packages:
      - swftools
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
